<?php $this->headTitle()->prepend($this->translate('Edit Restful Credentials')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-lg-8">
        <h2><?php echo $this->translate('Restful Credentials') ?></h2>
        <p><?php echo $this->translate('Create and manage the restful credentials.') ?></p>
    </div>
    <div class="col-lg-4">
    	<div class="text-right">
		    <a href="/admin/restfulcredentials/index/add" class="btn btn-default"><i class="fa fa-file"></i> <?php echo $this->translate('Add new')?></a>
		    <?php echo $this->formElement($form->get('submit')); ?>
		    <a href="/admin/restfulcredentials" class="btn btn-info"><i class="fa fa-list"></i> <?php echo $this->translate('List')?></a>
		</div>
	</div>
</div>

    <?php if ($this->error): ?>
        <div class="row">
	        <div class="col-lg-12">
	            <div class="alert alert-warning">
                    <?php echo $this->translate('There were one or more issues with your submission. Please correct them as indicated below.') ?>
	            </div>
	        </div>
        </div>
    <?php endif ?>

<div class="row">
	<div class="col-lg-12">
		<div class="tabbable" id="tabs">
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
				<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Permissions');?></a></li>
				<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Options');?></a></li>
			</ul>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('user_id')); ?>
                        <?php echo $this->formElement($form->get('user_id')); ?>
                        <?php echo $this->formElementErrors($form->get('user_id')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('secret')); ?>
                        <?php echo $this->formElement($form->get('secret')); ?>
                        <?php echo $this->formElementErrors($form->get('secret')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('requests')); ?>
                        <?php echo $this->formElement($form->get('requests')); ?>
                        <?php echo $this->formElementErrors($form->get('requests')); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('enabled')); ?>
                        <?php echo $this->formElement($form->get('enabled')); ?>
                        <?php echo $this->formElementErrors($form->get('enabled')); ?>
                    </div>
                </div>

                <div class="tab-pane" id="tab2">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('insert')); ?>
                        <?php echo $this->formElement($form->get('insert')); ?>
                        <?php echo $this->formElementErrors($form->get('insert')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('Delete')); ?>
                        <?php echo $this->formElement($form->get('Delete')); ?>
                        <?php echo $this->formElementErrors($form->get('Delete')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('list')); ?>
                        <?php echo $this->formElement($form->get('list')); ?>
                        <?php echo $this->formElementErrors($form->get('list')); ?>
                    </div>
                </div>
                <div class="tab-pane" id="tab3">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('description')); ?>
                        <?php echo $this->formElement($form->get('description')); ?>
                        <?php echo $this->formElementErrors($form->get('description')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('email')); ?>
                        <?php echo $this->formElement($form->get('email')); ?>
                        <?php echo $this->formElementErrors($form->get('email')); ?>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('url')); ?>
                        <?php echo $this->formElement($form->get('url')); ?>
                        <?php echo $this->formElementErrors($form->get('url')); ?>
                    </div>

                </div>
            </div>
		</div>
	</div>
</div>
<?php echo $this->formElement($form->get('id')); ?>

<?php echo $this->form()->closeTag() ?>
