<?php $this->headTitle()->prepend($this->translate('API Account Settings')); ?>
<?php $this->inlineScript()->appendFile($this->basePath() . '/js/ckeditor.js'); ?>

<?php
$event = $this->event;
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <br/>

            <div class="jumbotron">
                <div class="container">
                    <h1><?php echo $this->translate('API Request') ?>
                        <small><?php echo $this->translate('Your own API Token') ?></small>
                    </h1>
                    <p><?php echo $this->translate('To get started, create an account and generate an access token. All currently available endpoints are listed in this documentation. If something is missing, feel free to contact us at.') ?></p>

                    <p><a class="btn btn-success btn-lg" href="/cms/restful-api-v1.html"
                          role="button"><?php echo $this->translate('API Documentation') ?> »</a></p></div>
            </div>
        </div>
    </div>

    <?php if ($this->error): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-warning">
                    <?php echo $this->translate('There were one or more issues with your submission. Please correct them as indicated below.') ?>
                </div>
            </div>
        </div>
    <?php endif ?>

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-right"><?php echo $this->translate('All star (*) marked fields are mandatory!') ?></div>
            <br/>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('url')); ?> *
                <?php echo $this->formElement($form->get('url')); ?>
                <?php echo $this->formElementErrors($form->get('url')); ?>
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?> *
                <?php echo $this->formElement($form->get('email')); ?>
                <?php echo $this->formElementErrors($form->get('email')); ?>
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('description')); ?> *
                <?php echo $this->formElement($form->get('description')); ?>
                <?php echo $this->formElementErrors($form->get('description')); ?>
            </div>

        </div>
    </div>
    <div class="text-right">
        <?php echo $this->formElement($form->get('submit')); ?>
    </div>
</div>
</div>
<?php echo $this->form()->closeTag() ?>
